### ISSUE TITLE
Castle Daerion Encounter 2 Search tokens

### ISSUE THREAD

**Issue by Slytherc** [DelphiDie/TheShadowRune#1]
Hey,

Problem found in Castle Daerion encounter II:

I noticed that the search tokens do not dissapear once you searched them.

Greetings Slyther

**Comment by Maverick4jc** [comment]
Thank you Slyther! We really appreciate you testing out the campaign and helping us identify bugs or errors.  I fixed the search token error. We'll let you know when we release the next version.

**Comment by DelphiDie** [comment]
Thanks so much for testing and letting us know. 

I will close the issue once we released a new version which includes the fix (it shouldn't take too long).

**Comment by DelphiDie** [comment]
Maverick was able to fix the issue and I released an update for the campaign. You can download it in Valkyries download section.
