### ISSUE TITLE
Quest Wyrm Turn Part 2 Never end

### ISSUE THREAD

**Issue by Beeloshi** [DelphiDie/TheShadowRune#10]
Hello, 

I start the quest Wyrm Turn, win the first encounter, start the second part, kill all the monster before the Dragon Skull reach the exit and nothing happend... 
I could not win the quest, the only solution is to loose... 

Please help ;)

Thanks,

**Comment by Quantumrunner** [comment]
Hey Beeloshi,

was the quest won text already shown or did nothing happen at all?

**Comment by Beeloshi** [comment]
Hello,

Nothing happen.
I kill the last monster, finish the round... nothing appears !

Regards,

Nils BROUWER


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 13 mai 2020 à 19:01, Quantumrunner <notifications@github.com> a
écrit :

**Comment by Quantumrunner** [comment]
When did you download the campaign? The last change was 21 days ago. Afterwards a fix had been added that should fix the spawns. Maybe your savegame was created before?

In this case there is no change to fix your save. Unfortunately you will need to lose the encounter.

**Comment by Beeloshi** [comment]
Hello,

My save is more than 21 days old yes.

But i check my Valkyrie version and it's the last one...   2.4.07.
It's the last version no ?
Where could I find the last update to solve this issue ?

Thanks for your help,

Nils BROUWER


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 13 mai 2020 à 19:45, Quantumrunner <notifications@github.com> a
écrit :

**Comment by Quantumrunner** [comment]
You can't. The savegame contains the complete data of the campaign. Even if the data is fixed afterwards your save is still using the old data.

You could only start a new campaign instead or lose the mission to skip this problem.

**Comment by Beeloshi** [comment]
Ho ok...
Bad luck.
I will lose this encounter then.

Thanks for your help.

Nils BROUWER


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 13 mai 2020 à 19:53, Quantumrunner <notifications@github.com> a
écrit :

**Comment by Quantumrunner** [comment]
Sorry that there is not other solution. :(

There is a [ticket](https://github.com/NPBruce/valkyrie/issues/1186) for fixing this in the valkyrie github but I don't think this will be fixed anytime soon (or ever).

**Comment by Quantumrunner** [comment]
Closing this bug for now as we can't do anything about it until the save logic has been improved.
