### ISSUE TITLE
City menu won't load

### ISSUE THREAD

**Issue by gustavomicha** [DelphiDie/TheShadowRune#11]
Hi. I started my first campaign but after the first mission, I get to the city and see no menu nor options, just the map and heroes, and menu button.
If I save and exit, when I load I see a message saying "Unfortunately the merchants have nothing else to offer. You are unable to find another merchant", after clicking continue I see the message "After an exhausting day you grey to Arhynn", and then after clicking continue, nothing, just the map and a white square at the down-left bottom (see attached image).

I'm using valkyrie-linux-2.4.09 on Ubuntu 18.04.4.
I run Valkyrie by putting on the console "./Valkyrie.x86_64".

![20200629_171619](https://user-images.githubusercontent.com/33461763/86051852-79063a00-ba2c-11ea-8d88-30f62d51e68c.jpg)

**Comment by gustavomicha** [comment]
I tried staring a new campaign but the same thing happened

**Comment by Quantumrunner** [comment]
I have not been able to reproduce this. But I can't test on linux. Therefore this may be an OS problem.

Can you please check the error logs and upload them here?

~/.config/unity3d/NA/Valkyrie/Player.log

**Comment by gustavomicha** [comment]
Hi Quantumrunner, I see no error in the Player.log file, but to be honest i dont know what should i be trying to find. Im attaching it here if you want to take a look.
[Player.log](https://github.com/DelphiDie/TheShadowRune/files/4853405/Player.log)

**Comment by Quantumrunner** [comment]
It looks like it is not able to load the background image for the city in the linux version:
```
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Could not resolve file: '/tmp/Valkyrie/TSR.valkyrie/CP/city.jpg'
 
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

NullReferenceException: Object reference not set to an instance of an object
```

I think this better goes to the general Valkyrie issues section. Can you please reopen the issue here?

https://github.com/NPBruce/valkyrie/issues

**Comment by DelphiDie** [comment]
I think there was a similar problem in the past with the android version of Valkyrie. Perhaps it's related to the file being a .jpg file. We might be able to fix this, by including a .png file as a workaround, but this would increase the file size of the mod and ideally the android version should be able to work with .jpg files. So I think raising the issue on the Valkyrie Bugtracker would indeed be the best cause of action.

**Comment by parvusdomus** [comment]
It is actually a naming issue. Valkirie is trying to open city.jpg but in the TSR package you have included City.jpg (with a capital C). This is no issue in windows but in linux city and City are different filenames. To make it work you can simply open the TSR.valkyrie file and rename the CP/City.jpg file to CP/city.jpg. Worked for me.

Not sure it other files can have the same issue in this package.

**Comment by Quantumrunner** [comment]
Thank you @parvusdomus this was a very good finding. I have correct the image path. Furthermore I made a short check if any other pathes have a similar problem but could not find anything.

The update is live and should be available in Valkyrie in a few minutes. As usual you have to start a new campaign to make the changes be applied. Should not be a problem in this case since it was directly after the first quest.
