### ISSUE TITLE
Frozen Spire Encounter 1 Ettin bug

### ISSUE THREAD

**Issue by HeavyNerd** [DelphiDie/TheShadowRune#12]
Hey.
When Playing Frozen Spire Encounter 1 I encountered a bug concerning Ettins activation.
When it comes Ettins turn to activate its activation list is either empty or only has 
_-> Attack Hero_ 
on it. 

I think this might be a bug since it would make encounter way too easy.

I was playing on Android system Phone and I was using latest Valkyrie version 2.5.1

**Comment by Quantumrunner** [comment]
Thank you for feedback! I have fixed the problem by removing some unused (but for some reason shown) texts and updated the campaign. As usual these bug fixes won't work for your current campaign game but should automatically be loaded when you start a new campaign.
