### ISSUE TITLE
The Dawnblade Monster setup bug

### ISSUE THREAD

**Issue by HeavyNerd** [DelphiDie/TheShadowRune#13]
Hey.
During my last play session I was playing The Dawnblade quest and had reached the second encounter.

During setup I was told to put down 2 monster groups to different tiles on the map. Problem was that they were both Cave Spider groups. I was playing with 2 heroes so while I could have placed more minion spiders I had already reached the group limit. So the second tile had to be left empty.

I believe this is not supposed to happen?

I was playing on Android system Phone and I was using latest Valkyrie version 2.5.1

**Comment by Quantumrunner** [comment]
Thank you for feedback! I have fixed the problem and updated the campaign. As usual these bugfixes won't work for your current campaign game but should automatically be loaded when you start a new campaign.
