### ISSUE TITLE
Frozen Spire Crashes

### ISSUE THREAD

**Issue by HeavyNerd** [DelphiDie/TheShadowRune#14]
Hey! After the recent Ettin bug fix on The Frozen Spire quest I made a new game and just completed quests without actually playing to get back to this quest since I wanted to try it again now to see if I had given myself proper challenge last time when I just took control of the bugged Ettin.

I discovered that now the game contantly crashes on that quest. 
This happens usually when you press end turn for heroes. It feezes for couple of seconds and then exits the app. 

Quest: Frozen Spire Encounter 1
App version: 2.5.2
Device: Android phone

**Comment by Quantumrunner** [comment]
Looks like by fixing the ettin bug I had deleted some necessary activation logic for the dragons. I have restored this.

The bugfix is live but you will need to restart the campaign again to have the fixed data. Sorry for this!
