### ISSUE TITLE
Black screen when loading campaign - The Ritual of Shadow's Incantation Bug

### ISSUE THREAD

**Issue by bkblood** [DelphiDie/TheShadowRune#15]
Left Valkyrie running minimized over night to continue campaign the next day. When opening Valkyrie window I was presented with a black gameboard but could still see hero portraits. I saved the game, restarted Valkyrie, and when loaded is just completely black. 

Thank you.
[save2.vSave.txt](https://github.com/DelphiDie/TheShadowRune/files/7663939/save2.vSave.txt)

**Comment by bkblood** [comment]
The Ritual of Shadows quest is causing this bug.

Black screen bug happens IF Lord Merrick Finishes his 6 incanations before opening the door that Lord Merrick is actually in. If this happens. All game board peices dissappear.

**Comment by Quantumrunner** [comment]
Thanks for the bug details. I will try to fix this as soon as possible. Can you still proceed with your campaign by defeating Merrick earlier?

**Comment by Quantumrunner** [comment]
The issue has been fixed. Since Valkyrie is not able to update content mid campaign you will need to restart the campaign to get the fixes. Otherwise as a workaround just make sure to open all doors in encounter 1 of **Ritual of shadows** before the ritual value has reached 6.
