### ISSUE TITLE
Bug Issue

### ISSUE THREAD

**Issue by Jubez187** [DelphiDie/TheShadowRune#3]
Right at the main menu screen for the Shadow Rune (with the flavor text about the Jain and the others), I hit "Items" and then couldn't click out of it. It only showed my Knight's Shield and Sword, but my Elementalist's staff didn't have an image. Had to relog.

**Comment by DelphiDie** [comment]
Hello Jubez,
could you perhaps provide a screenshot or exact instructions to reproduce the problem? I wasn't able to reproduce the issue myself.

**Comment by DelphiDie** [comment]
Just to keep you updated: The issue has been fixed in Valkyrie Release 2.4.0.4.
