### ISSUE TITLE
Shop Functionality

### ISSUE THREAD

**Issue by AntonioFico** [DelphiDie/TheShadowRune#4]
Hi,

I'm playing with Shadow of Rune and i'm adapting Bloods Heiress for Valkyrie but i noticed that shop have some bugs...

i.e. when i ask to select only act1 QItem it filters only three objects...

What do you think about? Did you have same problem? How did you fix it?

Many thanks

**Comment by DelphiDie** [comment]
Hello Antonio,
I left a comment over at your post on the Valkyrie Bugtracker. As far as I understand it, this is not a bug in our campaign. So let's continue the discussion over there:
https://github.com/NPBruce/valkyrie/issues/1211

**Comment by AntonioFico** [comment]
Image in my first comment are from "Shadow of rune" where i changed traits to only "Act1" to reproduce the problem...

Same problem and same objects appeare in my game when i insert onl act1 tract.
