### ISSUE TITLE
Fat Goblin Encounter 2: Room 9B Search Token reward text

### ISSUE THREAD

**Issue by Liquidlogic1** [DelphiDie/TheShadowRune#7]
After successfully passing both tests of the search token in room 9B, the second line of text reads:

"You find EventSearch9BCaveTreasure.text gold. Discard this token" and does not give a number.

**Comment by DelphiDie** [comment]
Hello Liquidlogic,

thanks for reporting the error. I was able to find the cause, and I was able to fix it. Luckily it is just a display error, and you still received the 50 gold coins for passing the tests.

The next release will contain the fixed version.
