### ISSUE TITLE
Returning to town after quest - Shop not visible

### ISSUE THREAD

**Issue by horsefield** [DelphiDie/TheShadowRune#8]
I am running Valkyrie on Mint 19.2.  I transferred the entire D:RtL folder from a windows system to the linux system and thought I had appropriately imported the necessary files via command line.  The program seems to run correctly, and I was able to complete the first quest in the SR campaign, however upon completion and traveling to town, the shop interface does not appear to display properly.  The background sound effects change to ambient town sounds, and a small white box appears in the lower left of the display, but otherwise the map continues to fill the entire frame.  

If I save and continue, a blank black rectangle outlined in white appears at the top of the screen and the three options "Leave the City", "Ask other Merchant", and "Visit Black Market" appear, but choosing any option other than "Leave the City" again results in a white box at lower left and the quest map remaining in the rest of the field.  

This appears to occur both running in windowed or full screen mode.  

I am able to continue to the next quest, and I am able to view the "Items" in the party inventory correctly, so I appear to have the graphical assets available for equipment.

**Comment by DelphiDie** [comment]
Hello Horsefield,

sorry to hear you have a problem. I never encountered anything similar, but I also only tested the campaign on Windows. My guess would be, that there is a problem with the pathing system in regards to the background graphic files. The only other thing I could imagine would be some kind of codec problem, but it would be really strange if your system would be unable to open the graphics files. Unfortunately this is nothing I could fix. My suggestion would be to open a ticket on the valkyrie bugtracker and describe the problem over there. Perhaps the devs compiling the linux builds can reproduce the problem and fix it.

**Comment by DelphiDie** [comment]
Closing the issue, as we can't fix this kind of problem.
