### ISSUE TITLE
Multiple small bugs/issues found

### ISSUE THREAD

**Issue by Xyphistor** [DelphiDie/TheShadowRune#9]
New download of latest version of Valkyrie and downloaded Shadow Rune internally, so presumably the latest version.
Played through until the setup of the 2nd encounter of our 2nd Act II quest (Wyrm Turns).
Made a note of all typos, missing instructions, bugs, suggestions as we went along.
See attached Excel document for details!
[Shadow Rune Errata 1.xlsx](https://github.com/DelphiDie/TheShadowRune/files/4117797/Shadow.Rune.Errata.1.xlsx)

**Comment by DelphiDie** [comment]
Once again, thanks a lot for the feedback Xyphistor. Tantum already fixed a lot of the problems you reported and I'll push an update now. I'll keep this open, as a reminder until all issues are fixed.

@MrTantum could you upload a new excel sheet which indicates which problems are fixed / have to be worked on?

**Comment by Quantumrunner** [comment]
Here is the updated version:

https://1drv.ms/x/s!Avgu01I9GTFTgdlv_wDC9CBZTWeFGA?e=CFF16o

**Comment by Xyphistor** [comment]
Completed final 1.5 Act II quests and Finale, remaining errata list attached!
[Shadow Rune Errata 2.xlsx](https://github.com/DelphiDie/TheShadowRune/files/4506176/Shadow.Rune.Errata.2.xlsx)

**Comment by Quantumrunner** [comment]
Thanks. I have changed everything you mentioned. 

A lot of this stuff had already been fixed but we couldn't release it because of the valkyrie version.

**Comment by Quantumrunner** [comment]
I'll close this for now as the changes are live. Thanks again for the feedback.
